# Generated by Django 5.2.7 on 2025-12-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("RAZORPAY", "Razorpay"),
                    ("UPI_ON_DELIVERY", "UPI_ON_DELIVERY"),
                ],
                max_length=20,
            ),
        ),
    ]
