# Generated by Django 5.2.7 on 2026-03-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='reason_description',
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_type',
            field=models.CharField(choices=[('FULL_REFUND', 'Full Refund'), ('PARTIAL_REFUND', 'Partial Refund'), ('NO_REFUND', 'No Refund')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
