# Generated by Django 5.2.7 on 2026-04-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0003_remove_refund_reason_description_refund_refund_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("RAZORPAY", "Razorpay"),
                    ("UPI_ON_DELIVERY", "UPI_ON_DELIVERY"),
                    ("COD", "Cash On Delivery"),
                ],
                max_length=20,
            ),
        ),
    ]
