# Generated by Django 5.2.7 on 2025-12-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bargains", "0003_stockreservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockreservation",
            name="qty_pieces",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
