# Generated by Django 5.2.7 on 2026-02-14 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bargains', '0004_alter_stockreservation_qty_pieces'),
        ('inventory', '0018_storagelocation_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory'),
        ),
    ]
