# Generated by Django 5.2.7 on 2026-02-14 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bargains', '0005_chatsession_inventory'),
        ('inventory', '0018_storagelocation_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='inventory',
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='inventory.storagelocation'),
        ),
    ]
