# Generated by Django 5.2.7 on 2026-02-14 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bargains', '0006_remove_chatsession_inventory_and_more'),
        ('products', '0021_alter_weightoption_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='current_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_chat_sessions', to='products.product'),
        ),
    ]
