# Generated by Django 5.2.7 on 2026-03-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bargains', '0007_chatsession_current_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='current_product',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='cart_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='cart_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
