# Generated by Django 5.2.7 on 2026-03-01 11:49

import json
from django.db import migrations, models


def convert_text_to_json(apps, schema_editor):
    ChatMessage = apps.get_model('bargains', 'ChatMessage')
    for msg in ChatMessage.objects.all():
        if msg.text is not None and isinstance(msg.text, str):
            try:
                json.loads(msg.text)
            except Exception:
                msg.text = json.dumps(msg.text)
                msg.save(update_fields=['text'])


class Migration(migrations.Migration):

    dependencies = [
        ('bargains', '0008_remove_chatsession_current_product_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_text_to_json, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.JSONField(),
        ),
    ]
