# Generated by Django 5.2.7 on 2025-12-06 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("products", "0009_source_product_whatyouget_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_kg_before",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "stock_kg_after",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "stock_pieces_before",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "stock_pieces_after",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "wholesale_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("regular_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("display_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("bargain_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("min_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("UPDATE", "Updated"),
                            ("RESTOCK", "Restocked"),
                            ("SALE", "Sale"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("RETURN", "Return"),
                        ],
                        default="UPDATE",
                        max_length=20,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed changes in JSON format",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="inventory.inventory",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_history",
                        to="products.product",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_history",
                        to="inventory.storagelocation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inventory Histories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="inventory_i_created_14232c_idx"
                    ),
                    models.Index(
                        fields=["product", "-created_at"],
                        name="inventory_i_product_18dc38_idx",
                    ),
                    models.Index(
                        fields=["inventory", "-created_at"],
                        name="inventory_i_invento_8c1a8d_idx",
                    ),
                ],
            },
        ),
    ]
