# Generated by Django 5.2.7 on 2025-12-09 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventoryhistory"),
        ("products", "0009_source_product_whatyouget_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inventoryhistory",
            index=models.Index(
                fields=["storage_location", "-created_at"],
                name="inventory_i_storage_96936f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.UniqueConstraint(
                fields=("product", "storagelocation"),
                name="unique_product_storage_location",
            ),
        ),
    ]
