# Generated by Django 5.2.7 on 2025-12-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_inventoryhistory_inventory_i_storage_96936f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="is_bargainable",
            field=models.BooleanField(default=True),
        ),
    ]
