# Generated by Django 5.2.7 on 2025-12-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_inventory_is_bargainable"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="inventory",
            name="unique_product_storage_location",
        ),
    ]
