# Generated by Django 5.2.7 on 2025-12-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_remove_inventory_unique_product_storage_location"),
        ("products", "0014_rename_max_pics_product_max_pieces_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="pieces_per_kg_max",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="pieces_per_kg_min",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="serves_persons",
        ),
        migrations.AddField(
            model_name="inventory",
            name="max_pieces_per_kg",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum pieces in 1kg (e.g., 10 for 8-10)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="min_pieces_per_kg",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum pieces in 1kg (e.g., 8 for 8-10)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="sku",
            field=models.CharField(max_length=100, unique=True, blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inventory",
            name="stock_pieces",
            field=models.PositiveIntegerField(
                blank=True, help_text="Stock quantity in pieces", null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.UniqueConstraint(
                fields=("product", "storagelocation"),
                name="unique_product_storage_location",
            ),
        ),
    ]
