# Generated by Django 5.2.7 on 2025-12-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_remove_inventory_pieces_per_kg_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="sku",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
