# Generated by Django 5.2.7 on 2025-12-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_inventory_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagelocation",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude (e.g., 23.8103)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude (e.g., 90.4125)",
                max_digits=9,
                null=True,
            ),
        ),
    ]
