# Generated by Django 5.2.7 on 2025-12-11 12:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_storagelocation_latitude_storagelocation_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagelocation",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Lat/Lng of this storage location",
                null=True,
                srid=4326,
            ),
        ),
    ]
