# Generated by Django 5.2.7 on 2025-12-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_storagelocation_point"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storagelocation",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="storagelocation",
            name="longitude",
        ),
    ]
