# Generated by Django 5.2.7 on 2025-12-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_remove_storagelocation_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagelocation",
            name="point_lat",
            field=models.FloatField(
                blank=True, help_text="Latitude of this storage location", null=True
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="point_long",
            field=models.FloatField(
                blank=True, help_text="Longitude of this storage location", null=True
            ),
        ),
    ]
