# Generated by Django 5.2.7 on 2025-12-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_storagelocation_point_lat_storagelocation_point_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storagelocation",
            name="point_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=14,
                help_text="Latitude of this storage location",
                max_digits=17,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storagelocation",
            name="point_long",
            field=models.DecimalField(
                blank=True,
                decimal_places=14,
                help_text="Longitude of this storage location",
                max_digits=17,
                null=True,
            ),
        ),
    ]
