# Generated by Django 5.2.7 on 2025-12-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_alter_storagelocation_point_lat_and_more"),
        ("products", "0015_product_pack_weight_kg_product_sell_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_price__lte", models.F("bargain_price"))),
                name="ck_inventory_min_lte_bargain",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("bargain_price__lte", models.F("display_price"))),
                name="ck_inventory_bargain_lte_display",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("display_price__lte", models.F("regular_price"))),
                name="ck_inventory_display_lte_regular",
            ),
        ),
    ]
