# Generated by Django 5.2.7 on 2025-12-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_inventory_ck_inventory_min_lte_bargain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storagelocation",
            name="point_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=30,
                help_text="Latitude of this storage location",
                max_digits=35,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storagelocation",
            name="point_long",
            field=models.DecimalField(
                blank=True,
                decimal_places=30,
                help_text="Longitude of this storage location",
                max_digits=35,
                null=True,
            ),
        ),
    ]
