# Generated by Django 5.2.7 on 2026-01-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_storagelocation_point_lat_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='ck_inventory_min_lte_bargain',
        ),
        migrations.RemoveConstraint(
            model_name='inventory',
            name='ck_inventory_bargain_lte_display',
        ),
        migrations.RemoveConstraint(
            model_name='inventory',
            name='ck_inventory_display_lte_regular',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='bargain_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='display_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='regular_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='wholesale_price',
        ),
    ]
