# Generated by Django 5.2.7 on 2026-02-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_remove_inventory_ck_inventory_min_lte_bargain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryhistory",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("UPDATE", "Updated"),
                    ("RESTOCK", "Restocked"),
                    ("SALE", "Sale"),
                    ("PRICE_UPDATE", "PRICE_UPDATE"),
                    ("ADJUSTMENT", "Adjustment"),
                    ("RETURN", "Return"),
                ],
                default="UPDATE",
                max_length=20,
            ),
        ),
    ]
