# Generated by Django 5.2.7 on 2026-02-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_alter_inventoryhistory_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="stock_pieces",
            field=models.PositiveIntegerField(
                blank=True, default=0, help_text="Stock quantity in pieces", null=True
            ),
        ),
    ]
