# Generated by Django 5.2.7 on 2026-02-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_alter_inventory_stock_pieces"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagelocation",
            name="closing_time",
            field=models.TimeField(
                blank=True, help_text="Closing time (e.g., 10:00 PM)", null=True
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="opening_time",
            field=models.TimeField(
                blank=True, help_text="Opening time (e.g., 09:00 AM)", null=True
            ),
        ),
    ]
