# Generated by Django 5.2.7 on 2026-02-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_storagelocation_closing_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryTimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("cutoff_minutes", models.PositiveIntegerField(default=0)),
                (
                    "storagelocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_slots",
                        to="inventory.storagelocation",
                    ),
                ),
            ],
            options={
                "ordering": ["storagelocation", "start_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("storagelocation", "start_time", "end_time"),
                        name="unique_slot_per_location",
                    )
                ],
            },
        ),
    ]
