# Generated by Django 5.2.7 on 2026-02-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_deliverytimeslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverytimeslot",
            name="delivery_day",
            field=models.CharField(
                choices=[("TODAY", "Today"), ("TOMORROW", "Tomorrow")],
                default="TODAY",
                max_length=10,
            ),
        ),
    ]
