# Generated by Django 5.2.7 on 2026-02-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_deliverytimeslot_delivery_day"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deliverytimeslot",
            name="unique_slot_per_location",
        ),
        migrations.AddConstraint(
            model_name="deliverytimeslot",
            constraint=models.UniqueConstraint(
                fields=("storagelocation", "delivery_day", "start_time", "end_time"),
                name="unique_slot_per_location",
            ),
        ),
    ]
