# Generated by Django 5.2.7 on 2026-02-20 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_remove_deliverytimeslot_unique_slot_per_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverytimeslot",
            name="is_full",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="slot_step_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Gap between delivery slots in minutes (e.g., 30, 60).",
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(1440),
                ],
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="today_slots_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="today_slots_full",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="tomorrow_slots_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="tomorrow_slots_full",
            field=models.BooleanField(default=False),
        ),
    ]
