# Generated by Django 5.2.7 on 2026-02-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_deliverytimeslot_is_full_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagelocation",
            name="cutoff_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
