# Generated by Django 5.2.7 on 2026-02-26 07:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0023_storagelocation_cutoff_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagelocation",
            name="minimum_bargain_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Minimum order amount required to enable AI bargaining.",
                max_digits=10,
            ),
        ),
    ]
