# Generated by Django 5.2.7 on 2026-03-23 10:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0024_storagelocation_minimum_bargain_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagelocation",
            name="minimum_order_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Minimum amount required to order",
                max_digits=10,
            ),
        ),
    ]
