# Generated by Django 5.2.7 on 2026-03-31 05:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_storagelocation_minimum_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='minimum_pre_order_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum pre order amount required.', max_digits=10),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='partial_pay_pre_order_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pre order partial pay percentage', max_digits=10),
        ),
    ]
