# Generated by Django 5.2.7 on 2026-04-06 11:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_storagelocation_minimum_pre_order_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='max_cod_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1999.00'), help_text='Maximum order amount for Cash On Delivery', max_digits=10),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='min_cod_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('299.00'), help_text='Minimum order amount for Cash On Delivery', max_digits=10),
        ),
    ]
