# Generated by Django 5.2.7 on 2026-04-17 10:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_storagelocation_max_cod_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='packaging_cost_per_item',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Packaging cost per item', max_digits=10),
        ),
    ]
