# Generated by Django 5.2.7 on 2026-04-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_storagelocation_packaging_cost_per_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagelocation',
            name='packaging_cost_per_item',
        ),
    ]
