# Generated by Django 5.2.7 on 2025-12-13 08:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
       ('inventory', '0009_storagelocation_point'),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "storage_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_zones",
                        to="inventory.storagelocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Zone",
                "verbose_name_plural": "Delivery Zones",
            },
        ),
        migrations.CreateModel(
            name="DeliveryZoneUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for the delivery zone (e.g. 'Zone 1 - Koparkhairane')",
                        max_length=100,
                    ),
                ),
                (
                    "geojson_file",
                    models.FileField(
                        help_text="GeoJSON file containing a Polygon or MultiPolygon",
                        upload_to="delivery_zones/",
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(
                        default=False,
                        help_text="Has this file been processed into DeliveryZone?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "storage_location",
                    models.ForeignKey(
                        help_text="Hub that serves this zone",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.storagelocation",
                    ),
                ),
            ],
        ),
    ]
