# Generated by Django 5.2.7 on 2026-02-18 09:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_alter_deliverypartnerprofile_user"),
        ("inventory", "0021_remove_deliverytimeslot_unique_slot_per_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryChargeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_distance_km",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "max_distance_km",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[("FREE", "Free"), ("PAID", "Paid")],
                        default="PAID",
                        max_length=10,
                    ),
                ),
                (
                    "charge_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "storagelocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_charge_rules",
                        to="inventory.storagelocation",
                    ),
                ),
            ],
            options={
                "ordering": ["storagelocation", "min_distance_km"],
                "indexes": [
                    models.Index(
                        fields=["storagelocation", "is_active"],
                        name="delivery_de_storage_bd3f5b_idx",
                    ),
                    models.Index(
                        fields=[
                            "storagelocation",
                            "min_distance_km",
                            "max_distance_km",
                        ],
                        name="delivery_de_storage_fd2ddb_idx",
                    ),
                ],
            },
        ),
    ]
