# Generated by Django 5.2.7 on 2026-03-16 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0007_remove_deliveryotp_assignment_and_more"),
        ("orders", "0054_order_otp_sent_at_order_otp_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.order",
            ),
        ),
    ]
