# Generated by Django 5.2.7 on 2026-03-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0008_wallettransaction_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="account_holder_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="bank_ifsc",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="bank_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="upi_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
