# Generated by Django 5.2.7 on 2026-03-18 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_alter_withdrawalrequest_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypartnerprofile',
            name='salary',
        ),
    ]
