# Generated by Django 5.2.7 on 2026-03-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_remove_deliverypartnerprofile_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
