# Generated by Django 5.2.7 on 2026-02-11 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_inventory_stock_pieces'),
        ('store_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemanagerprofile',
            name='zone',
        ),
        migrations.AddField(
            model_name='storemanagerprofile',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_managers', to='inventory.storagelocation'),
        ),
        migrations.AlterField(
            model_name='storemanagerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='store_manager_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
