# Generated by Django 5.2.7 on 2026-02-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store_management", "0002_alter_storemanagerprofile_user"),
        ("store_management", "0002_remove_storemanagerprofile_zone_and_more"),
    ]

    operations = []
