# Generated by Django 5.2.7 on 2026-04-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0005_storemanagerprofile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemanagerprofile',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Inventory Manager', 'Inventory Manager'), ('Chef', 'Chef'), ('Helper', 'Helper')], default='Manager', max_length=50),
        ),
        migrations.AlterField(
            model_name='storemanagerprofile',
            name='shift_timing',
            field=models.CharField(choices=[('Morning (9AM - 5PM)', 'Morning (9AM - 5PM)'), ('Evening (2PM - 10PM)', 'Evening (2PM - 10PM)'), ('Night (9PM - 6AM)', 'Night (9PM - 6AM)'), ('Full Time', 'Full Time')], default='Full Time', max_length=20),
        ),
    ]
