# Generated by Django 5.2.7 on 2026-04-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_management", "0006_alter_storemanagerprofile_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storemanagerprofile",
            name="role",
            field=models.CharField(
                choices=[("Manager", "Manager"), ("Staff", "Staff")],
                default="Manager",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="storemanagerprofile",
            name="shift_timing",
            field=models.CharField(
                choices=[("Full Time", "Full Time")], default="Full Time", max_length=20
            ),
        ),
    ]
