# Generated by Django 5.2.7 on 2026-04-16 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_storagelocation_max_cod_amount_and_more'),
        ('store_management', '0008_pricehistory_new_buy_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_buying_vehicle', models.DecimalField(decimal_places=2, default=0, help_text='Vehicle/fuel for fish market trips per month', max_digits=10)),
                ('monthly_buying_misc', models.DecimalField(decimal_places=2, default=0, help_text='Ice, helpers, market fees during buying per month', max_digits=10)),
                ('packaging_cost_per_item', models.DecimalField(decimal_places=2, default=0, help_text='Cost to package ONE Fish item unit (bag + ice + wrapping). Masala ignored.', max_digits=6)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0, help_text='Shop rent', max_digits=10)),
                ('monthly_utilities', models.DecimalField(decimal_places=2, default=0, help_text='Electricity/Water', max_digits=10)),
                ('monthly_store_misc', models.DecimalField(decimal_places=2, default=0, help_text='Repairs, marketing', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_config', to='inventory.storagelocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
