# Generated by Django 5.2.7 on 2026-04-17 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_storagelocation_max_cod_amount_and_more'),
        ('store_management', '0009_storecostconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(help_text='Date from which these costs apply')),
                ('monthly_buying_vehicle', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_buying_misc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_utilities', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_store_misc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_snapshots', to='inventory.storagelocation')),
            ],
            options={
                'ordering': ['-effective_date'],
                'unique_together': {('storage_location', 'effective_date')},
            },
        ),
    ]
