# Generated by Django 5.2.7 on 2026-04-17 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_storagelocation_max_cod_amount_and_more'),
        ('store_management', '0010_storecostsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(help_text='Month (1-12)')),
                ('year', models.PositiveSmallIntegerField(help_text='Year (e.g. 2026)')),
                ('category', models.CharField(choices=[('FISH_COST', 'Fish Cost'), ('TRAVEL', 'Travel'), ('ICE', 'Ice'), ('CLEANING', 'Store Cleaning'), ('LABOUR', 'Labour'), ('OTHER', 'Other'), ('RENT', 'Store Rent'), ('UTILITIES', 'Utilities (Electricity/Water)'), ('STORE_MISC', 'Store Misc (Repairs/Marketing)')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_expenses', to='inventory.storagelocation')),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
                'indexes': [models.Index(fields=['storage_location', 'year', 'month'], name='store_manag_storage_f128d5_idx')],
            },
        ),
    ]
