# Generated by Django 5.2.7 on 2026-04-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0011_monthlyexpense'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storecostsnapshot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='storecostsnapshot',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='storecostsnapshot',
            name='storage_location',
        ),
        migrations.DeleteModel(
            name='StoreCostConfig',
        ),
        migrations.DeleteModel(
            name='StoreCostSnapshot',
        ),
    ]
