# Generated by Django 5.2.7 on 2026-04-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0012_alter_storecostsnapshot_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyexpense',
            name='cost_type',
            field=models.CharField(choices=[('VARIABLE', 'Variable Cost'), ('OPERATIONAL', 'Operational Cost')], default='VARIABLE', max_length=20),
        ),
    ]
