# Generated by Django 5.2.7 on 2026-04-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0013_monthlyexpense_cost_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpense',
            name='category',
            field=models.CharField(choices=[('FISH_COST', 'Fish Cost'), ('TRAVEL', 'Travel'), ('ICE', 'Ice'), ('PACKAGING', 'Packaging Cost'), ('CLEANING', 'Store Cleaning'), ('LABOUR', 'Labour'), ('OTHER', 'Other'), ('RENT', 'Store Rent'), ('UTILITIES', 'Utilities (Electricity/Water)'), ('STORE_MISC', 'Store Misc (Repairs/Marketing)')], max_length=50),
        ),
    ]
