# Generated by Django 5.2.7 on 2026-04-18 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0014_alter_monthlyexpense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricehistory',
            name='new_buy_price',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='old_buy_price',
        ),
    ]
