# Generated by Django 5.2.7 on 2026-04-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0015_remove_pricehistory_new_buy_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpense',
            name='category',
            field=models.CharField(choices=[('FISH_COST', 'Fish Cost'), ('MASALA_COST', 'Masala Cost'), ('TRAVEL', 'Travel'), ('ICE', 'Ice'), ('PACKAGING', 'Packaging Cost'), ('CLEANING', 'Store Cleaning'), ('LABOUR', 'Labour'), ('OTHER', 'Other'), ('RENT', 'Store Rent'), ('UTILITIES', 'Utilities (Electricity/Water)'), ('STORE_MISC', 'Store Misc (Repairs/Marketing)')], max_length=50),
        ),
    ]
