# Generated by Django 5.2.7 on 2026-04-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0016_alter_monthlyexpense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyexpense',
            name='custom_category',
            field=models.CharField(blank=True, help_text='Used when category is OTHER', max_length=100),
        ),
    ]
