# Generated by Django 5.2.7 on 2026-04-18 11:12

import django.utils.timezone
import datetime
from django.conf import settings
from django.db import migrations, models

def set_expense_date(apps, schema_editor):
    MonthlyExpense = apps.get_model('store_management', 'MonthlyExpense')
    for expense in MonthlyExpense.objects.all():
        try:
            expense.expense_date = datetime.date(expense.year, expense.month, 1)
        except Exception:
            pass
        expense.save(update_fields=['expense_date'])

    ExpenseHistory = apps.get_model('store_management', 'ExpenseHistory')
    for hist in ExpenseHistory.objects.all():
        try:
            hist.expense_date = datetime.date(hist.year, hist.month, 1)
        except Exception:
            pass
        hist.save(update_fields=['expense_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_remove_storagelocation_packaging_cost_per_item'),
        ('store_management', '0018_monthlyexpense_is_deleted_expensehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='monthlyexpense',
            name='store_manag_storage_f128d5_idx',
        ),
        migrations.AddField(
            model_name='expensehistory',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monthlyexpense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of the expense'),
        ),
        migrations.RunPython(set_expense_date, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='expensehistory',
            name='month',
        ),
        migrations.RemoveField(
            model_name='expensehistory',
            name='year',
        ),
        migrations.RemoveField(
            model_name='monthlyexpense',
            name='month',
        ),
        migrations.RemoveField(
            model_name='monthlyexpense',
            name='year',
        ),
        migrations.AlterModelOptions(
            name='monthlyexpense',
            options={'ordering': ['-expense_date', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='monthlyexpense',
            index=models.Index(fields=['storage_location', '-expense_date'], name='store_manag_storage_26d035_idx'),
        ),
    ]
