# Generated by Django 5.2.7 on 2026-04-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0019_alter_monthlyexpense_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpense',
            name='category',
            field=models.CharField(choices=[('FISH_COST', 'COGS (Fish)'), ('MASALA_COST', 'COGS (Masala)'), ('TRAVEL', 'Travel'), ('ICE', 'Ice'), ('PACKAGING', 'Packaging Cost'), ('CLEANING', 'Store Cleaning'), ('LABOUR', 'Labour'), ('OTHER', 'Other'), ('RENT', 'Store Rent'), ('UTILITIES', 'Utilities (Electricity/Water)'), ('STORE_MISC', 'Store Misc (Repairs/Marketing)'), ('SALARY', 'Salary')], max_length=50),
        ),
    ]
