# Generated by Django 5.2.7 on 2026-04-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0020_alter_monthlyexpense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpense',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
