# Generated by Django 5.2.7 on 2026-04-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0021_alter_monthlyexpense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensehistory',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
