# Generated by Django 5.2.7 on 2025-11-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="otp_code",
        ),
        migrations.AddField(
            model_name="otp",
            name="session_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="otp",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
