# Generated by Django 5.2.7 on 2025-11-13 08:21

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="IN"
                    ),
                ),
                (
                    "attempt_type",
                    models.CharField(
                        choices=[("send", "Send OTP"), ("verify", "Verify OTP")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("blocked", "Rate Limited"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "OTP Attempt",
                "verbose_name_plural": "OTP Attempts",
                "ordering": ["-attempted_at"],
                "indexes": [
                    models.Index(
                        fields=["phone_number", "attempt_type", "-attempted_at"],
                        name="accounts_ot_phone_n_db6ba7_idx",
                    ),
                    models.Index(
                        fields=["status", "-attempted_at"],
                        name="accounts_ot_status_21b23f_idx",
                    ),
                ],
            },
        ),
    ]
