# Generated by Django 5.2.8 on 2025-11-18 09:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_otpattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=255, unique=True),
                ),
                ("phone_verified", models.BooleanField(default=False)),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("total_orders", models.PositiveIntegerField(default=0)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profiles/images/%Y/%m/"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profiles/covers/%Y/%m/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "user_profiles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="user_profil_email_8a1024_idx"),
                    models.Index(
                        fields=["first_name", "last_name"],
                        name="user_profil_first_n_aff064_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("office", "Office"),
                            ("other", "Other"),
                        ],
                        default="home",
                        max_length=10,
                    ),
                ),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(db_index=True, max_length=100)),
                (
                    "country",
                    models.CharField(
                        db_index=True, default="Bangladesh", max_length=100
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Postal code must be 4-10 digits",
                                regex="^\\d{4,10}$",
                            )
                        ],
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Address",
                "verbose_name_plural": "User Addresses",
                "db_table": "user_addresses",
                "ordering": ["-is_default", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_default"],
                        name="user_addres_user_id_35ed52_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="user_addres_user_id_d90e90_idx",
                    ),
                ],
            },
        ),
    ]
