# Generated by Django 5.2.7 on 2025-11-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_useraddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Required for superusers only.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
