# Generated by Django 5.2.7 on 2025-12-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_user_email_alter_userprofile_email"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userprofile",
            name="user_profil_email_8a1024_idx",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_blocked_for_abuse",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_vip",
            field=models.BooleanField(default=False),
        ),
    ]
