# Generated by Django 5.2.7 on 2025-12-11 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_useraddress_latitude_useraddress_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="session_key",
            field=models.CharField(
                blank=True, help_text="For guest users", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
