# Generated by Django 5.2.7 on 2025-12-12 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_useraddress_session_key_alter_useraddress_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="postal_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Postal code must be 4-10 digits", regex="^\\d{4,10}$"
                    )
                ],
            ),
        ),
    ]
