# Generated by Django 5.2.7 on 2025-12-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_useraddress_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
