# Generated by Django 5.2.7 on 2025-12-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_useraddress_address_line_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="city",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
