# Generated by Django 5.2.7 on 2025-12-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_useraddress_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="recipient_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the person who will receive the delivery ",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="recipient_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
