# Generated by Django 5.2.7 on 2025-12-15 08:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_useraddress_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Lat/Lng of this useraddress location",
                null=True,
                srid=4326,
            ),
        ),
    ]
