# Generated by Django 5.2.7 on 2025-12-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_useraddress_recipient_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="address_type_other",
            field=models.CharField(
                blank=True,
                help_text="Specify if address type is 'Other' (e.g., Friend's House)",
                max_length=50,
                null=True,
            ),
        ),
    ]
