# Generated by Django 5.2.7 on 2025-12-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_useraddress_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="country",
            field=models.CharField(db_index=True, default="India", max_length=100),
        ),
    ]
