# Generated by Django 5.2.7 on 2025-12-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_useraddress_address_type_other"),
        ("accounts", "0017_alter_useraddress_country"),
    ]

    operations = []
