# Generated by Django 5.2.7 on 2025-12-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_merge_20251219_1133"),
        ("accounts", "0018_merge_20251219_1750"),
    ]

    operations = []
