# Generated by Django 5.2.7 on 2025-12-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_merge_20251220_1907"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="country",
            field=models.CharField(db_index=True, default="Bangladesh", max_length=100),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude (e.g., 23.8103)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude (e.g., 90.4125)",
                max_digits=9,
                null=True,
            ),
        ),
    ]
