# Generated by Django 5.2.7 on 2025-12-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_merge_20251220_1256"),
        (
            "accounts",
            "0020_remove_useraddress_point_alter_useraddress_country_and_more",
        ),
        ("accounts", "0021_alter_useraddress_country"),
    ]

    operations = []
