# Generated by Django 5.2.7 on 2025-12-21 07:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_merge_20251221_1300"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Lat/Lng of this useraddress location",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="country",
            field=models.CharField(db_index=True, default="India", max_length=100),
        ),
    ]
