# Generated by Django 5.2.7 on 2025-12-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_merge_20251220_1823"),
        ("accounts", "0023_useraddress_point_alter_useraddress_country"),
    ]

    operations = []
