# Generated by Django 5.2.7 on 2025-12-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_merge_20251222_1646"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=14,
                help_text="Latitude (e.g., 23.8103)",
                max_digits=17,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=14,
                help_text="Longitude (e.g., 90.4125)",
                max_digits=17,
                null=True,
            ),
        ),
    ]
