# Generated by Django 5.2.7 on 2026-01-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
