# Generated by Django 5.2.7 on 2026-01-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_useraddress_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='house_details',
            field=models.CharField(blank=True, help_text='Flat, House no., Building, Company, Apartment', max_length=255, null=True),
        ),
    ]
