# Generated by Django 5.2.7 on 2026-01-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_useraddress_house_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='address_line_1',
        ),
    ]
