# Generated by Django 5.2.7 on 2026-02-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_useraddress_address_line_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('STORE_MANAGER', 'Store Manager'), ('DELIVERY_PARTNER', 'Delivery Partner')], default='CUSTOMER', max_length=20),
        ),
    ]
