# Generated by Django 5.2.7 on 2026-03-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="address_type",
            field=models.CharField(
                blank=True,
                choices=[("home", "Home"), ("office", "Office"), ("other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
    ]
