# Generated by Django 5.2.7 on 2026-03-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="audience_type",
            field=models.CharField(
                choices=[("ALL", "All Users")], default="ALL", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("ORDER", "Order"),
                    ("PAYMENT", "Payment"),
                    ("DELIVERY", "Delivery"),
                    ("PROMO", "Promo"),
                    ("SYSTEM", "System"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ORDER_CONFIRMED", "Order Confirmed"),
                    ("ORDER_CANCELLED", "Order Cancelled"),
                    ("PAYMENT_SUCCESS", "Payment Success"),
                    ("PAYMENT_FAILED", "Payment Failed"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("PROMO_OFFER", "Promo Offer"),
                    ("SYSTEM_ALERT", "System Alert"),
                ],
                max_length=50,
            ),
        ),
    ]
