"""
Django settings for fishlo_main project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import platform
from datetime import timedelta
from pathlib import Path

from corsheaders.defaults import default_headers
from decouple import config
from .env_get_func import get_env_variable

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env_variable("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_variable("DEBUG", default=False, cast_type=bool)
ALLOWED_HOSTS = get_env_variable("ALLOWED_HOSTS", default="localhost").split(",")
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://192.168.0.245",
    "http://10.101.86.140",
    "http://10.0.0.2:8000",
    "http://10.0.0.2",
    "http://localhost:4173",
    "http://194.195.112.223",
    "http://194.195.112.223:8000",
    "http://194.195.112.223:5173",
    "http://fishlo.in",           # ADD THIS
    "http://www.fishlo.in",       # ADD THIS
    "https://fishlo.in",          # ADD THIS (for future SSL)
    "https://www.fishlo.in",      # ADD THIS (for future SSL)
    "https://figured-tomas-unfulminating.ngrok-free.dev"
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:4173",
    "http://194.195.112.223:8000",
    "http://194.195.112.223",
    "http://194.195.112.223:5173",
    "http://fishlo.in",           # ADD THIS
    "http://www.fishlo.in",       # ADD THIS
    "https://fishlo.in",          # ADD THIS (for future SSL)
    "https://www.fishlo.in", 
    "https://figured-tomas-unfulminating.ngrok-free.dev"
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-cart-id",
    "x-session-id",
]
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "phonenumber_field",
    "rest_framework_simplejwt",
    "corsheaders",
    "ckeditor",
    "ckeditor_uploader",
    "taggit",
    "django_filters",
    "rest_framework_simplejwt.token_blacklist",
    "django.contrib.gis",
    'django_celery_beat',
    'django_celery_results',
    
    # Local apps
    "accounts.apps.AccountsConfig",
    "products.apps.ProductsConfig",
    "orders.apps.OrdersConfig",
    "payments",
    "api",
    "home",
    "inventory.apps.InventoryConfig",
    "bargains",
    "promotions",
    "delivery.apps.DeliveryConfig",
    'policies',
    'store_management',
    'notifications',
    
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "fishlo_main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "fishlo_main.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    "default": {
        # 'ENGINE': 'django.db.backends.postgresql',
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": get_env_variable("DB_NAME", default="Fishlo_db"),
        "USER": get_env_variable("DB_USER", default="postgres"),
        "PASSWORD": get_env_variable("DB_PASSWORD", default=""),
        "HOST": get_env_variable("DB_HOST", default="localhost"),
        "PORT": get_env_variable("DB_PORT", default="5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    "accounts.backends.CustomAuthBackend",  # Your custom backend
    "django.contrib.auth.backends.ModelBackend",  # Keep as fallback
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.User"

# REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=1200),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=700),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# 2Factor API Configuration
TWOFACTOR_API_KEY = config("TWOFACTOR_API_KEY")


# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / "logs"
os.makedirs(LOGS_DIR, exist_ok=True)

# Phone Number Field Configuration
PHONENUMBER_DEFAULT_REGION = "IN"
PHONENUMBER_DB_FORMAT = "NATIONAL"


# Media URLs
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

CKEDITOR_UPLOAD_PATH = "uploads/"

OPENAI_API_KEY = get_env_variable("OPENAI_API_KEY")
OPENAI_MODEL = get_env_variable("OPENAI_MODEL")
CHAT_HISTORY_LENGTH = get_env_variable("CHAT_HISTORY_LENGTH", default=8, cast_type=int)

# Firebase
FIREBASE_CREDENTIALS_PATH = BASE_DIR / 'fishlo-aa252-firebase-adminsdk-fbsvc-93ba5a795f.json'

# Payment method keys and Ids
RAZORPAY_KEY_ID = get_env_variable("RAZORPAY_KEY_ID", default="")
RAZORPAY_KEY_SECRET = get_env_variable("RAZORPAY_KEY_SECRET", default="")

# Windows

# Windows
if platform.system() == "Windows":
    os.environ["PATH"] = (
        os.path.join(BASE_DIR, "env/Lib/site-packages/osgeo") + ";" + os.environ["PATH"]
    )
    os.environ["PROJ_LIB"] = (
        os.path.join(BASE_DIR, "env/Lib/site-packages/osgeo/data/proj")
        + ";"
        + os.environ["PATH"]
    )
    GDAL_LIBRARY_PATH = os.path.join(BASE_DIR, "env/Lib/site-packages/osgeo/gdal.dll")
elif platform.system() == "Darwin":
    GDAL_LIBRARY_PATH = "/opt/homebrew/opt/gdal/lib/libgdal.dylib"
    GEOS_LIBRARY_PATH = "/opt/homebrew/opt/geos/lib/libgeos_c.dylib"
else:
    os.environ['GDAL_LIBRARY_PATH'] = '/usr/lib/x86_64-linux-gnu/libgdal.so'



CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60
# Beat scheduler settings
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BROKER_URL = get_env_variable('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = 'django-db'

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CELERY_TIMEZONE = 'Asia/Kolkata'
CELERY_ENABLE_UTC = True

CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60

GOOGLE_MAPS_API_KEY=config("GOOGLE_MAPS_API_KEY")
NOTIFICATIONS_SKIP_FIREBASE = True  # flip to False when real app is ready


# APPEND_SLASH=False
EMAIL_HOST = get_env_variable("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = get_env_variable("EMAIL_PORT", default=587, cast_type=int)
EMAIL_HOST_USER = get_env_variable("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = get_env_variable("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = True

ADMIN_ORDER_NOTIFICATION_EMAIL = get_env_variable(
    "ADMIN_ORDER_NOTIFICATION_EMAIL", default="developer.rathan@gmail.com"
)
ADMIN_PANEL_BASE_URL = get_env_variable(
    "ADMIN_PANEL_BASE_URL", default="https://fishlo.in/admin/"
)

