# Generated by Django 5.2.7 on 2026-01-06 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('privacy', 'Privacy Policy'), ('quality', 'Quality Promise'), ('refund', 'Refund Policy'), ('terms', 'Terms of Service'), ('prices', 'Why Prices Change')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='The main paragraph text')),
                ('section_type', models.CharField(choices=[('text', 'Text Only'), ('list', 'List'), ('table', 'Table')], default='text', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order to display on page')),
                ('alert_text', models.CharField(blank=True, max_length=255, null=True)),
                ('alert_icon', models.CharField(blank=True, help_text='Symbol like ✓, ⓘ, ₹', max_length=10, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='policies.policypage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_key', models.CharField(help_text='List item text OR Table first column', max_length=255)),
                ('text_value', models.CharField(blank=True, help_text='Table second column (leave empty for lists)', max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='policies.policysection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
