# Generated by Django 5.2.7 on 2026-01-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['priority', '-created_at'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='order',
        ),
        migrations.AddField(
            model_name='faq',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers show first (e.g., 1 is highest priority)'),
        ),
    ]
