# Generated by Django 5.2.7 on 2026-03-02 03:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_alter_faq_options_remove_faq_order_faq_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionitem',
            name='section',
        ),
        migrations.AddField(
            model_name='policypage',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PolicySection',
        ),
        migrations.DeleteModel(
            name='SectionItem',
        ),
    ]
