# Generated by Django 5.2.7 on 2026-03-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_remove_sectionitem_section_policypage_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policypage',
            name='slug',
            field=models.CharField(choices=[('privacy', 'Privacy Policy'), ('quality', 'Quality Promise'), ('refund', 'Refund Policy'), ('terms', 'Terms of Service'), ('prices', 'Why Prices Change'), ('bargaining', 'How Bargaining Works'), ('ai_fisher', 'Meet Our AI Fisherwoman'), ('delivery', 'Delivery Information')], max_length=50, unique=True),
        ),
    ]
