# Generated by Django 5.2.7 on 2025-11-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_imagegallery_product_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
