# Generated by Django 5.2.7 on 2025-11-13 11:45

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_alter_category_deleted_at_alter_product_deleted_at_and_more",
        ),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Add tags like: fish, seafood, prawns",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
