# Generated by Django 5.2.7 on 2025-11-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured_image",
            field=models.ImageField(default=1, upload_to="images/featured_image/"),
            preserve_default=False,
        ),
    ]
