# Generated by Django 5.2.7 on 2025-12-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_featured_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="max_pics",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="max_serves",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="min_pics",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="min_serves",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
