# Generated by Django 5.2.7 on 2025-12-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0006_product_max_pics_product_max_serves_product_min_pics_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.TextField(),
        ),
    ]
