# Generated by Django 5.2.7 on 2025-12-03 10:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_product_short_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the source name/title",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload an image",
                        upload_to="sources/images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "content",
                    ckeditor.fields.RichTextField(
                        help_text="Enter the rich text content", verbose_name="Content"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Source",
                "verbose_name_plural": "Sources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WhatYouGet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name/title",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload an image",
                        upload_to="what_you_get/images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "content",
                    ckeditor.fields.RichTextField(
                        help_text="Enter the rich text content", verbose_name="Content"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "What You Get",
                "verbose_name_plural": "What You Get",
                "ordering": ["-created_at"],
            },
        ),
    ]
