# Generated by Django 5.2.7 on 2025-12-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_source_product_whatyouget_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="max_pics",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="max_serves",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="min_pics",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="min_serves",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
