# Generated by Django 5.2.7 on 2025-12-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_product_bargain_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="bargain_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="display_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="min_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="regular_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="wholesale_price",
        ),
    ]
