# Generated by Django 5.2.7 on 2025-12-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_remove_product_bargain_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="max_pics",
            new_name="max_pieces",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="min_pics",
            new_name="min_pieces",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
    ]
