# Generated by Django 5.2.7 on 2025-12-19 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_rename_max_pics_product_max_pieces_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pack_weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Pack size in kg (only if sell_type=PACK). Example: 0.500 for 500g",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sell_type",
            field=models.CharField(
                choices=[
                    ("WEIGHT", "By Weight (per kg)"),
                    ("PIECE", "By Piece"),
                    ("PACK", "Fixed Pack"),
                ],
                db_index=True,
                default="WEIGHT",
                max_length=20,
            ),
        ),
    ]
