# Generated by Django 5.2.7 on 2025-12-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_product_pack_weight_kg_product_sell_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="cut",
            name="product_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
