# Generated by Django 5.2.7 on 2026-01-27 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_storagelocation_point_lat_and_more'),
        ('products', '0017_recentlyviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('display_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bargain_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.storagelocation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('product', 'storage_location'), name='one_active_price_matrix'), models.CheckConstraint(condition=models.Q(('min_price__lte', models.F('bargain_price'))), name='min_price_is_lowest'), models.CheckConstraint(condition=models.Q(('bargain_price__lte', models.F('display_price'))), name='bargain_not_above_display'), models.CheckConstraint(condition=models.Q(('display_price__lte', models.F('regular_price'))), name='display_not_above_regular')],
            },
        ),
    ]
