# Generated by Django 5.2.7 on 2026-02-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_pricematrix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='min_weight',
        ),
    ]
