# Generated by Django 5.2.7 on 2026-02-02 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_rename_weight_product_min_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=3, help_text='Selectable weight in kg (0.25, 0.5, 1.0)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_options', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'weight_kg'],
                'unique_together': {('product', 'weight_kg')},
            },
        ),
    ]
