# Generated by Django 5.2.7 on 2026-02-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_weightoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightoption',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, help_text='Selectable weight in kg (0.25, 0.5, 1.0)', max_digits=5),
        ),
    ]
