# Generated by Django 5.2.7 on 2026-02-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_weightoption_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chat_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
