# Generated by Django 5.2.7 on 2026-03-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expected_net_weight_max_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max expected net weight as % of gross (e.g. 80 for 80%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='expected_net_weight_min_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Min expected net weight as % of gross (e.g. 70 for 70%)', max_digits=5, null=True),
        ),
    ]
