# Generated by Django 5.2.7 on 2026-04-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0023_product_expected_net_weight_max_per_kg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightoption",
            name="is_better_value",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="weightoption",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="Override display label. Leave blank to auto-generate e.g '450g–550g'",
                max_length=50,
                null=True,
            ),
        ),
    ]
