# Generated by Django 5.2.7 on 2026-04-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0024_weightoption_is_better_value_weightoption_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightoption",
            name="max_weight_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="weightoption",
            name="min_weight_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="weightoption",
            name="label",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
