# Generated by Django 5.2.7 on 2026-04-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0025_weightoption_max_weight_kg_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weightoption",
            name="max_weight_kg",
        ),
        migrations.RemoveField(
            model_name="weightoption",
            name="min_weight_kg",
        ),
    ]
