# Generated by Django 5.2.7 on 2026-04-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0026_remove_weightoption_max_weight_kg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightoption",
            name="max_pieces",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weightoption",
            name="min_pieces",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
