# Generated by Django 5.2.7 on 2026-04-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_weightoption_max_pieces_weightoption_min_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricematrix',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
