# Generated by Django 5.2.7 on 2026-04-18 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_pricematrix_buy_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricematrix',
            name='buy_price',
        ),
    ]
