import { useMemo } from "react";

export default function DashboardPagination({
  currentPage,
  totalCount,
  pageSize,
  onPageChange,
  siblingCount = 1,
}) {
  // Ensure valid numbers
  const safeTotalCount = totalCount || 0;
  const safePageSize = pageSize || 10;
  const totalPages = Math.ceil(safeTotalCount / safePageSize);

  const range = (start, end) => {
    let length = end - start + 1;
    return Array.from({ length }, (_, idx) => idx + start);
  };

  const paginationRange = useMemo(() => {
    const totalPageNumbers = siblingCount + 5; // sibling + current + first + last + dots

    // Case 1: If pages are fewer than max we want to show, show all
    if (totalPages <= totalPageNumbers) {
      return range(1, totalPages);
    }

    const leftSiblingIndex = Math.max(currentPage - siblingCount, 1);
    const rightSiblingIndex = Math.min(currentPage + siblingCount, totalPages);

    const shouldShowLeftDots = leftSiblingIndex > 2;
    const shouldShowRightDots = rightSiblingIndex < totalPages - 2;

    const firstPageIndex = 1;
    const lastPageIndex = totalPages;

    // Case 2: No left dots, but right dots shown (e.g., 1 2 3 4 5 ... 20)
    if (!shouldShowLeftDots && shouldShowRightDots) {
      let leftItemCount = 3 + 2 * siblingCount;
      let leftRange = range(1, leftItemCount);
      return [...leftRange, "...", totalPages];
    }

    // Case 3: No right dots, but left dots shown (e.g., 1 ... 16 17 18 19 20)
    if (shouldShowLeftDots && !shouldShowRightDots) {
      let rightItemCount = 3 + 2 * siblingCount;
      let rightRange = range(totalPages - rightItemCount + 1, totalPages);
      return [firstPageIndex, "...", ...rightRange];
    }

    // Case 4: Both left and right dots (e.g., 1 ... 9 10 11 ... 20)
    if (shouldShowLeftDots && shouldShowRightDots) {
      let middleRange = range(leftSiblingIndex, rightSiblingIndex);
      return [firstPageIndex, "...", ...middleRange, "...", lastPageIndex];
    }
  }, [totalCount, pageSize, siblingCount, currentPage, totalPages]);

  if (currentPage === 0 || totalPages <= 1) return null;

  return (
    <div className="d-flex justify-content-center mt-4">
      <nav aria-label="Orders pagination">
        <ul className="pagination dashboard-pagination gap-1">
          {/* Previous Button */}
          <li className={`page-item ${currentPage === 1 ? "disabled" : ""}`}>
            <button
              className="page-link rounded-circle"
              onClick={() => onPageChange(currentPage - 1)}
              disabled={currentPage === 1}
            >
              <i className="fas fa-chevron-left"></i>
            </button>
          </li>

          {/* Page Numbers Generated by Logic */}
          {paginationRange?.map((pageNumber, index) => {
            // Render the "..." (Dots)
            if (pageNumber === "...") {
              return (
                <li key={`dots-${index}`} className="page-item disabled">
                  <span className="page-link border-0 text-muted">...</span>
                </li>
              );
            }

            // Render clickable numbers
            return (
              <li
                key={pageNumber}
                className={`page-item ${
                  currentPage === pageNumber ? "active" : ""
                }`}
              >
                <button
                  className="page-link rounded-circle"
                  onClick={() => onPageChange(pageNumber)}
                >
                  {pageNumber}
                </button>
              </li>
            );
          })}

          {/* Next Button */}
          <li
            className={`page-item ${
              currentPage === totalPages ? "disabled" : ""
            }`}
          >
            <button
              className="page-link rounded-circle"
              onClick={() => onPageChange(currentPage + 1)}
              disabled={currentPage === totalPages}
            >
              <i className="fas fa-chevron-right"></i>
            </button>
          </li>
        </ul>
      </nav>
    </div>
  );
}
