# Generated by Django 5.2.7 on 2025-12-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("image", models.ImageField(upload_to="banners/%Y/%m/")),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("HOME_TOP_BANNER", "Home - Top Banner"),
                            ("HOME_MIDDLE_BANNER", "Home - Middle Banner"),
                            ("HOME_BOTTOM_BANNER", "Home - Bottom Banner"),
                            ("PLP_TOP_BANNER", "Product List - Top Banner"),
                            ("PLP_BETWEEN_ROWS", "Product List - Between Rows"),
                            ("CART_TOP_BANNER", "Cart - Top Banner"),
                            ("CART_BOTTOM_BANNER", "Cart - Bottom Banner"),
                            ("HOME_POPUP", "Home - Popup"),
                            ("BARGAIN_PROMO", "Bargain Feature Promo"),
                        ],
                        max_length=50,
                    ),
                ),
                ("link_url", models.URLField(blank=True, null=True)),
                ("priority", models.IntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["placement", "priority", "-starts_at"],
                "indexes": [
                    models.Index(
                        fields=["placement"], name="promotions__placeme_b9b345_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="promotions__is_acti_8d24c1_idx"
                    ),
                    models.Index(
                        fields=["starts_at", "ends_at"],
                        name="promotions__starts__964bb0_idx",
                    ),
                ],
            },
        ),
    ]
