# Generated by Django 5.2.7 on 2026-01-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='image_desktop',
        ),
        migrations.AddField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='banners/mobile/%Y/%m/'),
        ),
    ]
