# Generated by Django 5.2.7 on 2025-12-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderaddress",
            name="address_type_other",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
