# Generated by Django 5.2.7 on 2025-12-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderaddress_address_type_other"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderaddress",
            name="billing_address",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
