# Generated by Django 5.2.7 on 2025-12-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderaddress_billing_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_percentage",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="orderaddress",
            name="is_billing_same_as_shipping",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="orderaddress",
            name="country",
            field=models.CharField(default="India", max_length=100),
        ),
    ]
