# Generated by Django 5.2.7 on 2025-12-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_discount_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("Razorpay", "Razorpay")], default="COD", max_length=20
            ),
        ),
    ]
