# Generated by Django 5.2.7 on 2025-12-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="valid_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
