# Generated by Django 5.2.7 on 2025-12-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_discount_valid_from_alter_discount_valid_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="discount_value",
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_fixed_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discount fixed amount",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discount Percentage",
                max_digits=10,
                null=True,
            ),
        ),
    ]
