# Generated by Django 5.2.7 on 2025-12-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_remove_discount_discount_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="discount_fixed_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Discount fixed amount",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Discount Percentage",
                max_digits=10,
            ),
        ),
    ]
