# Generated by Django 5.2.7 on 2025-12-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_discount_discount_fixed_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_fixed_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Discount fixed amount",
                max_digits=10,
            ),
        ),
    ]
