# Generated by Django 5.2.7 on 2025-12-27 08:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_discount_fixed_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[("GST", "GST (Goods and Services Tax)")],
                        default="GST",
                        help_text="Type of tax applied",
                        max_length=10,
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Tax percentage (e.g., 5.00 for 5%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable/disable tax calculation"
                    ),
                ),
                (
                    "is_inclusive",
                    models.BooleanField(
                        default=False,
                        help_text="If True, tax is included in product price. If False, tax is added on top",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tax_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Configuration",
                "verbose_name_plural": "Tax Configuration",
            },
        ),
    ]
