# Generated by Django 5.2.7 on 2025-12-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_taxconfiguration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="code",
            field=models.CharField(
                help_text="Coupon code (up to 12 characters only)",
                max_length=12,
                unique=True,
            ),
        ),
    ]
