# Generated by Django 5.2.7 on 2025-12-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_alter_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordertracking",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Order Tracking",
                "verbose_name_plural": "Order Tracking",
            },
        ),
        migrations.AddField(
            model_name="ordertracking",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about this status update",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ordertracking",
            name="status",
            field=models.CharField(
                choices=[
                    ("order_placed", "Order Placed"),
                    ("processing", "Processing"),
                    ("packed_assigning", "Packed & Being Assigned"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                ],
                help_text="Current status of the order",
                max_length=20,
            ),
        ),
    ]
