# Generated by Django 5.2.7 on 2025-12-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_create_order_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                db_index=True, editable=False, max_length=50, unique=True
            ),
        ),
    ]
