# Generated by Django 5.2.7 on 2025-12-30 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_create_order_sequence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="current_tracking_status",
            field=models.CharField(
                blank=True,
                help_text="Current tracking status for timeline",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ordertracking",
            name="assigned_for_delivery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_man",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ordertracking",
            name="details",
            field=models.JSONField(
                blank=True, help_text="Additional flexible data", null=True
            ),
        ),
        migrations.AddField(
            model_name="ordertracking",
            name="updated_by",
            field=models.CharField(
                blank=True,
                help_text="Who updated this status",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                db_index=True, editable=False, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Razorpay", "Razorpay"),
                    ("UPI_ON_DELIVERY", "UPI_ON_DELIVERY"),
                ],
                default="Razorpay",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ordertracking",
            unique_together={("order", "status")},
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("user__isnull", False)),
                fields=("user",),
                name="unique_active_cart_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("user__isnull", True)),
                fields=("session_key",),
                name="unique_active_cart_per_session",
            ),
        ),
    ]
