# Generated by Django 5.2.7 on 2025-12-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_alter_order_order_number"),
        ("orders", "0016_order_current_tracking_status_and_more"),
    ]

    operations = []
