# Generated by Django 5.2.7 on 2025-12-31 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_merge_20251230_1922"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ordertracking",
            index=models.Index(
                fields=["order", "-timestamp"], name="orders_orde_order_i_06256d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ordertracking",
            index=models.Index(
                fields=["status", "timestamp"], name="orders_orde_status_a54e2e_idx"
            ),
        ),
    ]
