# Generated by Django 5.2.7 on 2025-12-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_ordertracking_orders_orde_order_i_06256d_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PROCESSING", "Processing"),
                    ("PACKED", "Packed"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
