# Generated by Django 5.2.7 on 2025-12-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0019_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_tracking_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PROCESSING", "Processing"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ordertracking",
            name="completed",
            field=models.BooleanField(
                default=False, help_text="If the Current Track is Complete"
            ),
        ),
        migrations.AddField(
            model_name="ordertracking",
            name="is_current",
            field=models.BooleanField(
                default=False, help_text="Only one tracking per order can be current"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PROCESSING", "Processing"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
