# Generated by Django 5.2.7 on 2025-12-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0021_alter_order_order_tracking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordertracking",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
