# Generated by Django 5.2.7 on 2026-01-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0022_alter_ordertracking_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_pdf",
            field=models.FileField(blank=True, null=True, upload_to="invoices/pdf/"),
        ),
    ]
