# Generated by Django 5.2.7 on 2026-01-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_invoice_generated_at_order_invoice_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderaddress',
            old_name='address_line_1',
            new_name='house_details',
        ),
    ]
