# Generated by Django 5.2.7 on 2026-02-03 08:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0024_rename_address_line_1_orderaddress_house_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="bonus_weight_in_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Free bonus weight in kg (AI only)",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="price_per_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price per kg at time of adding to cart",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="weight_in_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight in kg (e.g. 0.25, 0.5)",
                max_digits=6,
                null=True,
            ),
        ),
    ]
