# Generated by Django 5.2.7 on 2026-02-04 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_cartitem_bonus_weight_in_kg_cartitem_price_per_kg_and_more'),
        ('products', '0021_alter_weightoption_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.weightoption'),
        ),
    ]
