# Generated by Django 5.2.7 on 2026-02-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0026_cartitem_product_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total weight for this item",
                max_digits=10,
                null=True,
            ),
        ),
    ]
