# Generated by Django 5.2.7 on 2026-02-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0028_order_total_pieces"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total_pieces",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total in pieces", null=True
            ),
        ),
    ]
