# Generated by Django 5.2.7 on 2026-02-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0029_orderitem_total_pieces"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="total_pieces",
            new_name="pieces",
        ),
    ]
