# Generated by Django 5.2.7 on 2026-02-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0030_rename_total_pieces_orderitem_pieces"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="pieces",
            field=models.PositiveIntegerField(
                blank=True, help_text="Item in pieces", null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="pieces",
            field=models.PositiveIntegerField(
                blank=True, help_text="Item in pieces", null=True
            ),
        ),
    ]
