# Generated by Django 5.2.7 on 2026-02-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0031_cartitem_pieces_alter_orderitem_pieces"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight in kg (e.g. 0.25, 0.5)",
                max_digits=6,
                null=True,
            ),
        ),
    ]
