# Generated by Django 5.2.7 on 2026-02-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_orderitem_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='current_tracking_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_tracking_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('PACKED', 'Packed'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('PACKED', 'Packed'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], help_text='Current status of the order', max_length=20),
        ),
    ]
