# Generated by Django 5.2.7 on 2026-02-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_remove_order_current_tracking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for order cancellation', null=True),
        ),
    ]
