# Generated by Django 5.2.7 on 2026-02-11 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_order_cancellation_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who updated this status', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_status_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
