# Generated by Django 5.2.7 on 2026-02-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0035_order_created_by_order_customer_name_and_more"),
        ("orders", "0036_alter_ordertracking_updated_by"),
    ]

    operations = []
