# Generated by Django 5.2.7 on 2026-02-11 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0037_merge_20260211_2023"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="purchase_type",
            field=models.CharField(
                choices=[
                    ("WALK_IN_CUSTOMER", "Walk in customer"),
                    ("HOME_DELIVERY", "Home delivery"),
                ],
                default="HOME_DELIVERY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
