# Generated by Django 5.2.7 on 2026-02-12 13:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0038_order_purchase_type_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderaddress",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, help_text="order address pointer", null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Razorpay", "Razorpay"),
                    ("UPI_ON_DELIVERY", "UPI_ON_DELIVERY"),
                    ("CASH", "CASH"),
                ],
                default="Razorpay",
                max_length=20,
            ),
        ),
    ]
