# Generated by Django 5.2.7 on 2026-02-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0039_orderaddress_point_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderaddress",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orderaddress",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="orderaddress",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
