# Generated by Django 5.2.7 on 2026-02-14 15:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_alter_orderaddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='bargain_session_id',
            field=models.CharField(blank=True, help_text='Reference to AI negotiation session (for audit trail)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount from negotiation (for display)', max_digits=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_bargained',
            field=models.BooleanField(default=False, help_text="Whether this item's price was negotiated via AI"),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='negotiated_price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final negotiated price per kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='original_price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original display price before negotiation', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_locked_until',
            field=models.DateTimeField(blank=True, help_text='Price is guaranteed until this time (1 hour after negotiation)', null=True),
        ),
    ]
