# Generated by Django 5.2.7 on 2026-02-14 07:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0040_alter_orderaddress_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="adjustable_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
