# Generated by Django 5.2.7 on 2026-02-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0041_cartitem_bargain_session_id_cartitem_discount_amount_and_more",
        ),
        ("orders", "0041_order_adjustable_amount"),
    ]

    operations = []
