# Generated by Django 5.2.7 on 2026-02-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_deliverytimeslot"),
        ("orders", "0042_merge_20260217_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_day",
            field=models.CharField(
                blank=True,
                choices=[("TODAY", "Today"), ("TOMORROW", "Tomorrow")],
                default="TODAY",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="inventory.deliverytimeslot",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_slot_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_slot_label",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_slot_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
