# Generated by Django 5.2.7 on 2026-02-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0043_order_delivery_day_order_delivery_slot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_day",
            field=models.CharField(
                blank=True, default="TODAY", max_length=10, null=True
            ),
        ),
    ]
