# Generated by Django 5.2.7 on 2026-02-19 04:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0044_alter_order_delivery_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
