# Generated by Django 5.2.7 on 2026-02-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0045_alter_order_discount_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price at time of adding to cart",
                max_digits=10,
                null=True,
            ),
        ),
    ]
