# Generated by Django 5.2.7 on 2026-02-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_merge_20260218_0045'),
        ('orders', '0046_alter_cartitem_unit_price'),
    ]

    operations = [
    ]
