# Generated by Django 5.2.7 on 2026-02-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0047_merge_20260219_2244"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="token_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="token_number",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
