# Generated by Django 5.2.7 on 2026-02-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0049_create_order_token_seq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordertracking",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Current location of shipment",
                max_length=755,
                null=True,
            ),
        ),
    ]
