# Generated by Django 5.2.7 on 2026-03-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0053_alter_order_status_alter_ordertracking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="otp_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="otp_session_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
