# Generated by Django 5.2.7 on 2026-03-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0054_order_otp_sent_at_order_otp_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="expected_net_weight_max_per_kg_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Max expected net weight as % of gross (e.g. 80 for 80%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="expected_net_weight_min_per_kg_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Min expected net weight as % of gross (e.g. 70 for 70%)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
