# Generated by Django 5.2.7 on 2026-03-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0056_orderitem_custom_note_orderitem_custom_product_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="custom_product_name",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="entered_price",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="entered_weight",
        ),
    ]
