# Generated by Django 5.2.7 on 2026-03-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0057_remove_orderitem_custom_product_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="sell_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WEIGHT", "By Weight (per kg)"),
                    ("PIECE", "By Piece"),
                    ("PACK", "Fixed Pack"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
