# Generated by Django 5.2.7 on 2026-03-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0058_orderitem_sell_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sell_type',
            field=models.CharField(blank=True, choices=[('WEIGHT', 'By Weight (per kg)'), ('PIECE', 'By Piece'), ('PACK', 'Fixed Pack')], default='WEIGHT', max_length=10, null=True),
        ),
    ]
