# Generated by Django 5.2.7 on 2026-03-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0059_alter_orderitem_sell_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Razorpay', 'Razorpay'), ('UPI_ON_DELIVERY', 'UPI_ON_DELIVERY'), ('UPI_ONLINE', 'UPI_ONLINE'), ('CASH', 'CASH')], default='Razorpay', max_length=20),
        ),
    ]
