# Generated by Django 5.2.7 on 2026-03-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0060_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Weight in kg (e.g. 0.25, 0.5)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Total weight for this item",
                max_digits=10,
                null=True,
            ),
        ),
    ]
