# Generated by Django 5.2.7 on 2026-03-25 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0025_storagelocation_minimum_order_amount"),
        ("orders", "0061_alter_orderitem_product_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="storage_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="inventory.storagelocation",
            ),
        ),
    ]
