# Generated by Django 5.2.7 on 2026-03-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0062_order_storage_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="discount_source",
            field=models.CharField(
                choices=[
                    ("PERCENTAGE", "Percentage"),
                    ("FIXED_AMOUNT", "Fixed Amount"),
                ],
                default="BOTH",
                max_length=20,
            ),
        ),
    ]
