# Generated by Django 5.2.7 on 2026-03-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0063_discount_discount_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="discount_source",
            field=models.CharField(
                choices=[
                    ("BOTH", "BOTH"),
                    ("ONLINE", "ONLINE"),
                    ("MANUAL_STORE", "MANUAL_STORE"),
                ],
                default="BOTH",
                max_length=20,
            ),
        ),
    ]
