# Generated by Django 5.2.7 on 2026-03-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0064_alter_discount_discount_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Weight in kg (e.g. 0.25, 0.5)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
