# Generated by Django 5.2.7 on 2026-03-27 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0065_alter_orderitem_product_weight'),
        ('orders', '0065_paymentmethodlog'),
    ]

    operations = [
    ]
