# Generated by Django 5.2.7 on 2026-03-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0066_merge_20260327_1740"),
        ("orders", "0066_merge_20260327_1904"),
        ("orders", "0066_merge_20260328_1454"),
    ]

    operations = []
