# Generated by Django 5.2.7 on 2026-03-30 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0066_merge_20260327_1740'),
        ('orders', '0066_merge_20260328_1454'),
    ]

    operations = [
    ]
