# Generated by Django 5.2.7 on 2026-03-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0067_merge_20260328_1852'),
        ('orders', '0067_merge_20260330_1422'),
    ]

    operations = [
    ]
