# Generated by Django 5.2.7 on 2026-03-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0068_merge_20260330_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_source',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], default='PUBLIC', max_length=20),
        ),
    ]
