# Generated by Django 5.2.7 on 2026-04-01 05:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0069_alter_discount_discount_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_collected',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount collected in cash by the delivery person', max_digits=10),
        ),
    ]
