# Generated by Django 5.2.7 on 2026-04-01 05:02

from django.db import migrations

from decimal import Decimal

def backfill_cash_collected(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    orders_to_update = Order.objects.filter(status="DELIVERED", remaining_amount__gt=0, payment_method__in=["UPI_ON_DELIVERY", "CASH"])
    for order in orders_to_update:
        order.cash_collected = order.remaining_amount
        order.remaining_amount = Decimal("0.00")
        order.payment_status = "PAID"
        order.save(update_fields=["cash_collected", "remaining_amount", "payment_status"])

def reverse_backfill(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0070_order_cash_collected'),
    ]

    operations = [
        migrations.RunPython(backfill_cash_collected, reverse_code=reverse_backfill),
    ]
