# Generated by Django 5.2.7 on 2026-04-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0071_backfill_cash_collected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Razorpay", "Razorpay"),
                    ("UPI_ON_DELIVERY", "UPI_ON_DELIVERY"),
                    ("UPI_ONLINE", "UPI_ONLINE"),
                    ("CASH", "CASH"),
                    ("COD", "Cash On Delivery"),
                ],
                default="Razorpay",
                max_length=20,
            ),
        ),
    ]
