# Generated by Django 5.2.7 on 2026-04-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0071_backfill_cash_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='updated_from',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('STORE_DASHBOARD', 'Store Dashboard'), ('ADMIN_DASHBOARD', 'Admin Dashboard'), ('DELIVERY_APP', 'Delivery App'), ('CUSTOMER', 'Customer')], default='SYSTEM', help_text='Source of the status update (e.g. Store Dashboard, Admin, Delivery App)', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Razorpay', 'Razorpay'), ('UPI_ON_DELIVERY', 'UPI_ON_DELIVERY'), ('UPI_ONLINE', 'UPI_ONLINE'), ('CASH', 'CASH'), ('COD', 'Cash On Delivery')], default='Razorpay', max_length=20),
        ),
    ]
