# Generated by Django 5.2.7 on 2026-04-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0072_alter_order_payment_method"),
        ("orders", "0072_ordertracking_updated_from_and_more"),
    ]

    operations = []
