# Generated by Django 5.2.7 on 2026-04-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0073_merge_20260406_1920"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="weight_option_label_snapshot",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
