# Generated by Django 5.2.7 on 2026-04-13 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0074_orderitem_weight_option_label_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptShareLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_file",
                    models.FileField(blank=True, null=True, upload_to="receipts/"),
                ),
                (
                    "short_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("phone", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_clicked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_links",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
