# Generated by Django 5.2.7 on 2026-04-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0075_receiptsharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fish buying cost snapshot at time of order', max_digits=10, null=True),
        ),
    ]
