# Generated by Django 5.2.7 on 2026-04-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0075_receiptsharelink"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="manual_receipt_pdf",
            field=models.FileField(blank=True, null=True, upload_to="manual_receipts/"),
        ),
    ]
