# Generated by Django 5.2.7 on 2026-04-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0076_orderitem_buy_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='packaging_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total packaging cost for this item, frozen at order time', max_digits=8),
        ),
    ]
