# Generated by Django 5.2.7 on 2026-04-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0077_orderitem_packaging_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='packaging_cost',
        ),
    ]
