# Generated by Django 5.2.7 on 2026-04-18 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0078_remove_orderitem_packaging_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='buy_price',
        ),
    ]
