# Generated by Django 5.2.7 on 2026-04-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0076_order_manual_receipt_pdf'),
        ('orders', '0079_remove_orderitem_buy_price'),
    ]

    operations = [
    ]
