# Generated by Django 5.2.7 on 2026-04-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0080_merge_20260418_1559"),
        ("orders", "0080_merge_20260418_1625"),
    ]

    operations = []
